import type { Metadata } from "next";
import "./../styles/globals.css";
import Header from "@/components/core/header";
import ContextLayout from "@/actions/UserContext/UserProvider";

export const metadata: Metadata = {
  title: "Pitput",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContextLayout>
          <Header />
          <main>{children}</main>
        </ContextLayout>
      </body>
    </html>
  );
}
